### ISSUE TITLE
Error occured during sending OTP

### ISSUE THREAD

**Issue by aasimtaif** [RishiBakshii/mern-ecommerce#1]
![Screenshot from 2024-05-10 20-40-35](https://github.com/RishiBakshii/mern-ecommerce/assets/83891519/6dfe3d5f-7bdf-497b-a283-6a63092e9f9a)

**Comment by RishiBakshii** [comment]
hi @aasimtaif thanks for raising an issue here, i guess this issue is occuring because of the expired email sending password. I will update the password with new one then you will be able to receive the otp's via mernshoponline@gmail.com
