### ISSUE TITLE
Cors error

### ISSUE THREAD

**Issue by keyurdevani289** [RishiBakshii/mern-ecommerce#4]
https://github.com/RishiBakshii/mern-ecommerce/issues/2 
i am facing same this issue 
i have cloned your latest code @RishiBakshii 

![357710076-2490d186-9ea1-4ed0-86ed-106fc0e76bc6](https://github.com/user-attachments/assets/55db4d04-82f6-4b21-b3b0-4f8437f89267)
![357710217-b3b6c69f-82d4-4fee-9db4-2e7c2db093a8](https://github.com/user-attachments/assets/7cb25fed-d99a-4adf-b7a6-4d7cd36390cc)

**Comment by RishiBakshii** [comment]
@chavla2890  @keyurdevani289  thankyou for raising this issue here, i will work on this and fix it as soon as possible

**Comment by RishiBakshii** [comment]
hi @chavla2890 @keyurdevani289, i have fixed the issue now the online version of this project will also work fine. Thankyou
