### ISSUE TITLE
password typing is not hidden

### ISSUE THREAD

**Issue by osteensouthpaw** [RishiBakshii/mern-ecommerce#5]
When i type in my password, it is not hidden

**Comment by RishiBakshii** [comment]
hi @osteensouthpaw  thankyou for raising an issue here, if you are willing to solve this issue by contributing in this open source project then that would be great

**Comment by RishiBakshii** [comment]
hi @osteensouthpaw do you wanna raise a pull request for this?

**Comment by OMIIIEE** [comment]
may i work on this issue ? I am new to open source and want to do my first contribution

**Comment by OMIIIEE** [comment]
hi @RishiBakshii , may I work on this issue ?

**Comment by RishiBakshii** [comment]
hi @OMIIIEE , yes yes for sure please work on this issue and  i will merge your pull request
